= Changelog

:sectnums!:

== link:++https://github.com/saltstack-formulas/mysql-formula/compare/v0.55.0...v0.55.1++[0.55.1^] (2021-03-23)

=== Bug Fixes

* *salt-user:* redirect error output from user access checks
(https://github.com/saltstack-formulas/mysql-formula/commit/4cb4c05e48272c8073b0798afa8b31f232d12674[4cb4c05^])

=== Continuous Integration

* *commitlint:* ensure `upstream/master` uses main repo URL [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/e20d7c69d12777365ff95c841decfe7dc05c4227[e20d7c6^])
* *gemfile+lock:* use `ssf` customised `kitchen-docker` repo [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/63561c0a2f236722b4449717e83b421a021d7093[63561c0^])
* *gitlab-ci:* add `rubocop` linter (with `allow_failure`) [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/d08b960daf910f9c386523ae3d942d851cca2802[d08b960^])
* *kitchen+ci:* use latest pre-salted images (after CVE) [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/1af83d1fac432c9208c968182979090348dab69c[1af83d1^])
* *kitchen+gitlab-ci:* use latest pre-salted images [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/b27382a76cf3f2fd40c5dc6934175186f2065720[b27382a^])
* *pre-commit:* update hook for `rubocop` [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/86397f6390a6f5aab812dda258d3438674798af3[86397f6^])

== link:++https://github.com/saltstack-formulas/mysql-formula/compare/v0.54.2...v0.55.0++[0.55.0^] (2020-12-16)

=== Bug Fixes

* *percona:* fix startswith error
(https://github.com/saltstack-formulas/mysql-formula/commit/6b39bda366af83b7080e056b2f3e00408689c44b[6b39bda^])
* *redhat:* added missing client socket
(https://github.com/saltstack-formulas/mysql-formula/commit/b0f370cf8b60e2e8a9e281f945ae2ab435a2e63c[b0f370c^])
* *redhat:* update python library, add missing deps
(https://github.com/saltstack-formulas/mysql-formula/commit/3cab000c89e5032dd7b7fc0c7cd7a68696e2445b[3cab000^])
* *server:* fix `salt-lint` violations [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/2d1c7c30e60b2f8a50a3964b82cb43cc5d54709b[2d1c7c3^])

=== Continuous Integration

* *gitlab-ci:* use GitLab CI as Travis CI replacement
(https://github.com/saltstack-formulas/mysql-formula/commit/fb50e26f6a2bfa38f8ed57981f4ba730cf43c34d[fb50e26^])
* *pre-commit:* add to formula [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/11e646082ec3846045edde20411615c7c0f3479b[11e6460^])
* *pre-commit:* enable/disable `rstcheck` as relevant [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/87cb5b7c4f6096902dd97a4eeda2c238de5b0fa9[87cb5b7^])
* *pre-commit:* finalise `rstcheck` configuration [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/92bf43a3b79fa3b1cee0f43de98dd9aac1ea2a6c[92bf43a^])

=== Features

* *credentials:* add socket access
(https://github.com/saltstack-formulas/mysql-formula/commit/1c70b0abc106fbce2d7f95feaf9f02dd64cddfcf[1c70b0a^])

== link:++https://github.com/saltstack-formulas/mysql-formula/compare/v0.54.1...v0.54.2++[0.54.2^] (2020-08-27)

=== Bug Fixes

* *indent:* properly indent file.directory block
(https://github.com/saltstack-formulas/mysql-formula/commit/7791268d133d557d21414365db59dc14c8f97f74[7791268^]),
closes
https://github.com/saltstack-formulas/mysql-formula/issues/250[#250^]

== link:++https://github.com/saltstack-formulas/mysql-formula/compare/v0.54.0...v0.54.1++[0.54.1^] (2020-08-24)

=== Bug Fixes

* *freebsd:* upgrade to mysql57-server
(https://github.com/saltstack-formulas/mysql-formula/commit/ec681995b4f7e23a8dbec63809d3704f19ec9299[ec68199^])

== link:++https://github.com/saltstack-formulas/mysql-formula/compare/v0.53.0...v0.54.0++[0.54.0^] (2020-07-10)

=== Continuous Integration

* *kitchen:* use `saltimages` Docker Hub where available [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/b37a8a7c970cb30ed18f04c4103c5f553557699d[b37a8a7^])

=== Features

* *socket_authentication:* allow unix_socket authentication
(https://github.com/saltstack-formulas/mysql-formula/commit/8eccd5a68cadde02f54467a7fb9e370d2ee7d574[8eccd5a^])

== link:++https://github.com/saltstack-formulas/mysql-formula/compare/v0.52.7...v0.53.0++[0.53.0^] (2020-06-01)

=== Continuous Integration

* *kitchen+travis:* use latest pre-salted images
(https://github.com/saltstack-formulas/mysql-formula/commit/7ea518a3919f1a59bc6ae821bc0df7577629059a[7ea518a^])
* *travis:* add notifications => zulip [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/8adfc4bb4fbb49548cf46d277a0403b89c180b1a[8adfc4b^])

=== Features

* *focal:* add settings for `ubuntu-20.04`
(https://github.com/saltstack-formulas/mysql-formula/commit/0d77164f394909ec371f39cb41a4920c82e75052[0d77164^])

== link:++https://github.com/saltstack-formulas/mysql-formula/compare/v0.52.6...v0.52.7++[0.52.7^] (2020-05-19)

=== Bug Fixes

* *osfamilymap.yaml:* update SUSE defaults
(https://github.com/saltstack-formulas/mysql-formula/commit/8ee79a7bb03488e4c3632a1dcfe143696a11aad5[8ee79a7^])

=== Continuous Integration

* *gemfile.lock:* add to repo with updated `Gemfile` [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/9e9fa3e3d15e25ad22f75eae61af4883c79b7c0f[9e9fa3e^])
* *kitchen+travis:* remove `master-py2-arch-base-latest` [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/c1dddc3a8d561847094bbe23fe2c764c8fdf79de[c1dddc3^])
* *workflows/commitlint:* add to repo [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/b4c65702b91e8813741bf72008e41d1d8dfc735d[b4c6570^])

== link:++https://github.com/saltstack-formulas/mysql-formula/compare/v0.52.5...v0.52.6++[0.52.6^] (2020-04-17)

=== Bug Fixes

* *reload-modules:* do `reload_modules` on py module installation
(https://github.com/saltstack-formulas/mysql-formula/commit/2b6e704c96d0373aadb56f90d758c960f538abdb[2b6e704^])

=== Continuous Integration

* *gemfile:* restrict `train` gem version until upstream fix [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/04f75a7a3b43de9425a8f36dc202b7ecf0c4f856[04f75a7^])
* *kitchen:* avoid using bootstrap for `master` instances [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/ef7a2ce2d857dd271ec0704ab951c8337cb6b64e[ef7a2ce^])
* *travis:* use `major.minor` for `semantic-release` version [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/b4f5f79781631d7d31061b880df3066ac5bc5860[b4f5f79^])

== link:++https://github.com/saltstack-formulas/mysql-formula/compare/v0.52.4...v0.52.5++[0.52.5^] (2019-12-10)

=== Bug Fixes

* *db_load:* preserve space between -h and -p on the db load `cmd.wait`
(https://github.com/saltstack-formulas/mysql-formula/commit/a05f263f4b9eac52a5854fd57a6a24f997ccb291[a05f263^])

== link:++https://github.com/saltstack-formulas/mysql-formula/compare/v0.52.3...v0.52.4++[0.52.4^] (2019-12-03)

=== Styles

* remove previous line from jinja directives
(https://github.com/saltstack-formulas/mysql-formula/commit/ec0e2a765a587d0df94b0afb9f7a4ef78a5319ab[ec0e2a7^])

== link:++https://github.com/saltstack-formulas/mysql-formula/compare/v0.52.2...v0.52.3++[0.52.3^] (2019-12-03)

=== Bug Fixes

* *mac_shortcut.sh:* fix `shellcheck` errors
(https://github.com/saltstack-formulas/mysql-formula/commit/7b309f8da272ebdcb36dbfa7619a0fc9872a79a7[7b309f8^])
* *release.config.js:* use full commit hash in commit link [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/3f51b8bbc231a7455e6763b415221abff636d8a2[3f51b8b^])

=== Continuous Integration

* *kitchen:* use `debian-10-master-py3` instead of `develop` [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/5efe9387fde63e0c09d99d5771f3b623fb934242[5efe938^])
* *kitchen:* use `develop` image until `master` is ready (`amazonlinux`)
 [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/63bfb4a0f25b62bdc45c1738d438ce5ec64f2183[63bfb4a^])
* *kitchen+travis:* upgrade matrix after `2019.2.2` release [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/27ac5a3f684325a8e15736bb85d4774807061534[27ac5a3^])
* *travis:* apply changes from build config validation [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/d520848c815a9c2815ee3f1943e3e3962a26c7cf[d520848^])
* *travis:* opt-in to `dpl v2` to complete build config validation [skip
ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/1a8d914fbd5e43f78ee2334b9c5ccd51ee65ad57[1a8d914^])
* *travis:* quote pathspecs used with `git ls-files` [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/3fb5a82de66dda9a05decc5ee7263729ef913533[3fb5a82^])
* *travis:* run `shellcheck` during lint job [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/0931835f1cfc77022a43242bd3ab04cbed2a3a02[0931835^])
* *travis:* update `salt-lint` config for `v0.0.10` [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/1512279c2eac26638720461cc7e847d93d2c77d6[1512279^])
* *travis:* use build config validation (beta) [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/40d4b9763f252f5811d31b2b2df156260bde2b6d[40d4b97^])

=== Documentation

* *contributing:* remove to use org-level file instead [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/6afcc80396dc4ec2044d8611f18a6ed9075c6a52[6afcc80^])
* *readme:* update link to `CONTRIBUTING` [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/01f25a3ebfbf59d1db2bec73bc5fef9d8bcafd7e[01f25a3^])

=== Performance Improvements

* *travis:* improve `salt-lint` invocation [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/1980c634b9021c7d29be914bd2a63ddf3c31c8ad[1980c63^])

== link:++https://github.com/saltstack-formulas/mysql-formula/compare/v0.52.1...v0.52.2++[0.52.2^] (2019-10-11)

=== Bug Fixes

* *rubocop:* add fixes using `rubocop --safe-auto-correct`
(https://github.com/saltstack-formulas/mysql-formula/commit/fca3b04[fca3b04^])

=== Continuous Integration

* merge travis matrix, add `salt-lint` & `rubocop` to `lint` job
(https://github.com/saltstack-formulas/mysql-formula/commit/b2b8863[b2b8863^])
* *travis:* merge `rubocop` linter into main `lint` job
(https://github.com/saltstack-formulas/mysql-formula/commit/26dc562[26dc562^])

== link:++https://github.com/saltstack-formulas/mysql-formula/compare/v0.52.0...v0.52.1++[0.52.1^] (2019-10-10)

=== Bug Fixes

* *server.sls:* fix `salt-lint` errors
(https://github.com/saltstack-formulas/mysql-formula/commit/764dd0c[764dd0c^])
* *user.sls:* fix `salt-lint` errors
(https://github.com/saltstack-formulas/mysql-formula/commit/a014e55[a014e55^])

=== Continuous Integration

* *kitchen:* change `log_level` to `debug` instead of `info`
(https://github.com/saltstack-formulas/mysql-formula/commit/75fd8dc[75fd8dc^])
* *kitchen:* install required packages to bootstrapped `opensuse` [skip
ci] (https://github.com/saltstack-formulas/mysql-formula/commit/8b89ebc)
* *kitchen:* use bootstrapped `opensuse` images until `2019.2.2` [skip
ci] (https://github.com/saltstack-formulas/mysql-formula/commit/4bdaab7)
* *platform:* add `arch-base-latest` (commented out for now) [skip ci]
(https://github.com/saltstack-formulas/mysql-formula/commit/5c20c9b[5c20c9b^])
* *yamllint:* add rule `empty-values` & use new `yaml-files` setting
(https://github.com/saltstack-formulas/mysql-formula/commit/2322ff6[2322ff6^])
* merge travis matrix, add `salt-lint` & `rubocop` to `lint` job
(https://github.com/saltstack-formulas/mysql-formula/commit/00494d5[00494d5^])
* use `dist: bionic` & apply `opensuse-leap-15` SCP error workaround
(https://github.com/saltstack-formulas/mysql-formula/commit/05b1cef[05b1cef^])

== link:++https://github.com/saltstack-formulas/mysql-formula/compare/v0.51.0...v0.52.0++[0.52.0^] (2019-08-17)

=== Features

* *yamllint:* include for this repo and apply rules throughout
(https://github.com/saltstack-formulas/mysql-formula/commit/9f739fa[9f739fa^])

== link:++https://github.com/saltstack-formulas/mysql-formula/compare/v0.50.0...v0.51.0++[0.51.0^] (2019-08-08)

=== Bug Fixes

* *connector:* fix typos (connnector) and missing `enabled`
(https://github.com/saltstack-formulas/mysql-formula/commit/bdee94a[bdee94a^])

=== Features

* *linux:* archlinux support (no osmajorrelase grain)
(https://github.com/saltstack-formulas/mysql-formula/commit/4b4ad88[4b4ad88^])

== link:++https://github.com/saltstack-formulas/mysql-formula/compare/v0.49.0...v0.50.0++[0.50.0^] (2019-07-12)

=== Features

* *semantic-release:* implement for this formula
(https://github.com/saltstack-formulas/mysql-formula/commit/1d2e2f5[1d2e2f5^])
